### ISSUE TITLE
can't build for production

### ISSUE THREAD

**Issue by TimWeidner** [raneio/editlayer#7]
I get these errors after following the guide:

```
These dependencies were not found:

* core-js/modules/es6.array.find in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/content/Editor.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/panel/ItemsFromArray.vue?vue&type=script&lang=js& and 6 others
* core-js/modules/es6.function.name in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/content/Editor.vue?vue&type=script&lang=js& and 13 others
* core-js/modules/es6.number.constructor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/core/Notification.vue?vue&type=script&lang=js&
* core-js/modules/es6.object.keys in ./src/store/modules/firestore.js, ./src/store/modules/projects.js and 1 other
* core-js/modules/es6.regexp.constructor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/editors/common/BaseEditor.vue?vue&type=script&lang=js&
* core-js/modules/es6.regexp.match in ./src/utils/buildStructure.js
* core-js/modules/es6.regexp.replace in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/navigation/Breadcrumb.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/navigation/BackButton.vue?vue&type=script&lang=js& and 11 others
* core-js/modules/es6.regexp.split in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/content/Editor.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/navigation/Breadcrumb.vue?vue&type=script&lang=js& and 7 others
* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/editors/previews/Text.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/editors/previews/Code.vue?vue&type=script&lang=js&
* core-js/modules/es6.string.includes in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/content/Editor.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/panel/ItemsFromArray.vue?vue&type=script&lang=js& and 7 others
* core-js/modules/es6.string.link in ./src/store/modules/notifications.js
* core-js/modules/es6.string.starts-with in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/panel/ItemsFromArray.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/editors/common/BaseEditor.vue?vue&type=script&lang=js& and 4 others
* core-js/modules/es7.array.includes in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/content/Editor.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/panel/ItemsFromArray.vue?vue&type=script&lang=js& and 7 others
* core-js/modules/es7.object.get-own-property-descriptors in ./src/store/modules/firestore.js, ./src/store/modules/projects.js and 1 other
* core-js/modules/web.dom.iterable in ./src/store/modules/firestore.js, ./src/store/modules/projects.js and 1 other

To install them, you can run: npm install --save core-js/modules/es6.array.find core-js/modules/es6.function.name core-js/modules/es6.number.constructor core-js/modules/es6.object.keys core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.string.includes core-js/modules/es6.string.link core-js/modules/es6.string.starts-with core-js/modules/es7.array.includes core-js/modules/es7.object.get-own-property-descriptors core-js/modules/web.dom.iterable
 ERROR  Build failed with errors.
Error: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "npx vue-cli-service build --mode production"
    at makeError (D:\dev\editlayer\node_modules\execa\index.js:174:9)
    at module.exports.sync (D:\dev\editlayer\node_modules\execa\index.js:338:15)
    at handleShell (D:\dev\editlayer\node_modules\execa\index.js:117:9)
    at Function.module.exports.shellSync (D:\dev\editlayer\node_modules\execa\index.js:361:43)
    at D:\dev\editlayer\scripts\deploy.js:116:11
    at Object.<anonymous> (D:\dev\editlayer\scripts\deploy.js:132:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12) {
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /q /s /c "npx vue-cli-service build --mode production"',
  timedOut: false
}
```

**Comment by raneio** [comment]
At what stage did this happen?

**Comment by TimWeidner** [comment]
At ```npm run deploy production``` on
https://editlayer.rane.io/documentation/getting-started/deploy

**Comment by raneio** [comment]
Okey. Has `npm run init` given any errors?

**Comment by TimWeidner** [comment]
Nope, went through, completely smooth. The usual npm vulnerabilities and warnings, but other than that pretty usual installation.

**Comment by raneio** [comment]
Did you tried install core-js?
`npm install --save core-js`
